"""Evidence-bound wafer anomaly reports generated by a local OpenAI-compatible LLM."""
from __future__ import annotations

import json
import re
from collections import Counter
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from config import (
    REPORT_LLM_API_KEY,
    REPORT_LLM_BASE_URL,
    REPORT_LLM_MODEL,
    REPORT_MAX_RECORDS,
)


REPORT_FIELDS = (
    "dn_no", "lot_id", "product_id", "platform", "station", "machine",
    "scan_time", "defect_type", "edx_elements", "edx_bg", "map_location",
    "dft_location", "total_wafers", "scanned_wafers", "bad_wafers",
)
CHART_FIELDS = (
    ("defect_type", "缺陷类型分布"),
    ("machine", "设备 / 腔体分布"),
    ("station", "站点分布"),
    ("platform", "平台分布"),
    ("map_location", "晶圆位置分布"),
    ("product_id", "产品分布"),
)
class ReportServiceError(RuntimeError):
    """Raised when the local report model cannot produce a usable response."""


def _present(value: Any) -> bool:
    return value is not None and str(value).strip() not in {"", "—", "UNKNOWN", "nan"}


def compact_records(results: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Keep only auditable fields and cap prompt size."""
    compact: list[dict[str, Any]] = []
    for item in results[:REPORT_MAX_RECORDS]:
        fields = item.get("fields") or {}
        row = {
            "record_id": str(item.get("record_id") or fields.get("dn_no") or "UNKNOWN"),
            "retrieval_score": round(float(item.get("score") or 0), 4),
        }
        row.update({key: fields[key] for key in REPORT_FIELDS if _present(fields.get(key))})
        if _present(fields.get("text_content")):
            # Most text_content repeats the structured fields above.  A short
            # tail keeps unique notes while preserving the 8K local model window.
            row["description"] = str(fields["text_content"])[:180]
        compact.append(row)
    return compact


def build_visualizations(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Build deterministic charts from retrieved records; the LLM cannot invent counts."""
    charts: list[dict[str, Any]] = []
    for field, title in CHART_FIELDS:
        counts = Counter(str(row[field]).strip() for row in records if _present(row.get(field)))
        if not counts:
            continue
        charts.append({
            "field": field,
            "title": title,
            "items": [{"label": label, "count": count} for label, count in counts.most_common(8)],
        })
    return charts


def _extract_json(text: str) -> dict[str, Any]:
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text, flags=re.IGNORECASE).strip()
    try:
        value = json.loads(text)
    except json.JSONDecodeError:
        start, end = text.find("{"), text.rfind("}")
        if start < 0 or end <= start:
            raise ReportServiceError("报告模型没有返回可解析的 JSON")
        try:
            value = json.loads(text[start:end + 1])
        except json.JSONDecodeError as exc:
            raise ReportServiceError(f"报告模型返回格式异常：{exc.msg}") from exc
    if not isinstance(value, dict):
        raise ReportServiceError("报告模型返回的顶层结构不是对象")
    return value


def model_status(timeout: int = 3) -> dict[str, Any]:
    request = Request(
        f"{REPORT_LLM_BASE_URL.rstrip('/')}/models",
        headers={"Authorization": f"Bearer {REPORT_LLM_API_KEY}"},
    )
    try:
        with urlopen(request, timeout=timeout) as response:
            payload = json.loads(response.read().decode("utf-8"))
        return {"ok": True, "model": REPORT_LLM_MODEL, "models": payload.get("data", [])}
    except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as exc:
        return {"ok": False, "model": REPORT_LLM_MODEL, "detail": str(exc)}


def _knowledge_query(query: str, records: list[dict[str, Any]], additional_context: str) -> str:
    evidence_terms = []
    for row in records[:10]:
        evidence_terms.extend(str(row.get(key, "")) for key in (
            "defect_type", "machine", "station", "platform", "map_location", "dft_location"
        ) if _present(row.get(key)))
    return " ".join(filter(None, [query, additional_context, " ".join(evidence_terms)]))[:2000]


def _retrieve_knowledge(query: str, records: list[dict[str, Any]], additional_context: str):
    from utils.analysis_knowledge import get_analysis_knowledge_store
    try:
        items = get_analysis_knowledge_store().retrieve(
            _knowledge_query(query, records, additional_context)
        )
        return items, {"ok": True, "source": "qdrant", "count": len(items)}
    except Exception as exc:
        # Report generation remains available, but the absence of methodology
        # retrieval is explicitly disclosed to the model and the user.
        return [], {"ok": False, "source": "qdrant", "count": 0, "detail": str(exc)}


def generate_report(
    query: str,
    results: list[dict[str, Any]],
    additional_context: str = "",
    input_metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    records = compact_records(results)
    if not records:
        raise ReportServiceError("没有可用于生成报告的检索记录")

    knowledge, knowledge_status = _retrieve_knowledge(query, records, additional_context)
    knowledge_prompt = [{
        "knowledge_id": item.get("knowledge_id"),
        "title": item.get("title"),
        "organization": item.get("organization"),
        "summary": str(item.get("summary_zh") or "")[:220],
        "analysis_methods": list(item.get("analysis_methods", []))[:2],
        "limitations": item.get("limitations"),
    } for item in knowledge]

    system_prompt = """你是晶圆制造异常分析助手。事实结论只允许基于用户输入和检索记录，禁止虚构设备、批次、量测、元素、时间或根因。专业知识条目只用于选择分析方法和验证动作，绝不能被当成当前晶圆已发生事实。明确区分：观察事实、推断假设、待验证事项。根因只能写成按优先级排列的假设；每个事实结论必须列出 record_id 作为证据。用户文字属于现场补充信息，必须注明为“用户输入”，不可伪装成数据库记录。用户上传图片只通过检索到的历史记录形成间接证据，不能凭图片猜测未识别的量测值。若证据不足，直接说明不足。输出简体中文且只能输出一个 JSON 对象，不要 Markdown，不要思考过程。JSON schema：
{
  "title": "string",
  "executive_summary": "string",
  "observations": [{"finding":"string","source_ids":["string"]}],
  "root_cause_hypotheses": [{"rank":1,"hypothesis":"string","confidence":"高|中|低","evidence":"string","source_ids":["string"],"validation_actions":["string"]}],
  "immediate_actions": ["string"],
  "verification_plan": ["string"],
  "knowledge_applied": [{"knowledge_id":"string","application":"string"}],
  "limitations": ["string"]
}"""
    user_prompt = (
        f"当前异常/检索目标：{query or '未提供自然语言描述'}\n"
        f"用户追加的现场文字：{additional_context or '无'}\n"
        f"输入材料元数据：{json.dumps(input_metadata or {}, ensure_ascii=False)}\n"
        f"检索命中记录（共 {len(records)} 条）：\n"
        + json.dumps(records, ensure_ascii=False, separators=(",", ":"))
        + "\n从 Qdrant 检索的行业方法知识（仅可作方法论，不是当前晶圆事实）：\n"
        + json.dumps(knowledge_prompt, ensure_ascii=False, separators=(",", ":"))
    )
    payload = {
        "model": REPORT_LLM_MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.2,
        "top_p": 0.85,
        "presence_penalty": 1.2,
        "max_tokens": 2200,
        "reasoning_effort": "none",
        "response_format": {"type": "json_object"},
    }
    request = Request(
        f"{REPORT_LLM_BASE_URL.rstrip('/')}/chat/completions",
        data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {REPORT_LLM_API_KEY}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urlopen(request, timeout=180) as response:
            response_payload = json.loads(response.read().decode("utf-8"))
        content = response_payload["choices"][0]["message"]["content"]
    except HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")[:500]
        raise ReportServiceError(f"报告模型请求失败（HTTP {exc.code}）：{detail}") from exc
    except (URLError, TimeoutError) as exc:
        raise ReportServiceError(f"无法连接本地报告模型：{exc}") from exc
    except (KeyError, IndexError, TypeError, json.JSONDecodeError) as exc:
        raise ReportServiceError("报告模型响应结构异常") from exc

    return {
        "model": REPORT_LLM_MODEL,
        "source_count": len(records),
        "source_ids": [row["record_id"] for row in records],
        "report": _extract_json(str(content)),
        "visualizations": build_visualizations(records),
        "methodology_references": [{
            "knowledge_id": item.get("knowledge_id"),
            "title": f"{item.get('organization', '')}：{item.get('title', '')}",
            "url": item.get("url"),
            "score": item.get("score"),
        } for item in knowledge],
        "knowledge_status": knowledge_status,
        "input_metadata": input_metadata or {},
    }
